import { Region, Province, City, Barangay } from '@/types';

export const regions: Region[] = [
  { id: 'NCR', name: 'National Capital Region (NCR)' },
  { id: 'CAR', name: 'Cordillera Administrative Region (CAR)' },
  { id: 'I', name: 'Region I - Ilocos Region' },
  { id: 'II', name: 'Region II - Cagayan Valley' },
  { id: 'III', name: 'Region III - Central Luzon' },
  { id: 'IVA', name: 'Region IV-A - CALABARZON' },
  { id: 'IVB', name: 'Region IV-B - MIMAROPA' },
  { id: 'V', name: 'Region V - Bicol Region' },
  { id: 'VI', name: 'Region VI - Western Visayas' },
  { id: 'VII', name: 'Region VII - Central Visayas' },
  { id: 'VIII', name: 'Region VIII - Eastern Visayas' },
  { id: 'IX', name: 'Region IX - Zamboanga Peninsula' },
  { id: 'X', name: 'Region X - Northern Mindanao' },
  { id: 'XI', name: 'Region XI - Davao Region' },
  { id: 'XII', name: 'Region XII - SOCCSKSARGEN' },
  { id: 'XIII', name: 'Region XIII - Caraga' },
  { id: 'BARMM', name: 'Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)' },
];

export const provinces: Province[] = [
  { id: 'NCR-MM', name: 'Metro Manila', regionId: 'NCR' },
  { id: 'CAR-ABR', name: 'Abra', regionId: 'CAR' },
  { id: 'CAR-APY', name: 'Apayao', regionId: 'CAR' },
  { id: 'CAR-BEN', name: 'Benguet', regionId: 'CAR' },
  { id: 'CAR-IFU', name: 'Ifugao', regionId: 'CAR' },
  { id: 'CAR-KAL', name: 'Kalinga', regionId: 'CAR' },
  { id: 'CAR-MTP', name: 'Mountain Province', regionId: 'CAR' },
  { id: 'I-ILN', name: 'Ilocos Norte', regionId: 'I' },
  { id: 'I-ILS', name: 'Ilocos Sur', regionId: 'I' },
  { id: 'I-LUN', name: 'La Union', regionId: 'I' },
  { id: 'I-PAN', name: 'Pangasinan', regionId: 'I' },
  { id: 'II-BAT', name: 'Batanes', regionId: 'II' },
  { id: 'II-CAG', name: 'Cagayan', regionId: 'II' },
  { id: 'II-ISA', name: 'Isabela', regionId: 'II' },
  { id: 'II-NVZ', name: 'Nueva Vizcaya', regionId: 'II' },
  { id: 'II-QUI', name: 'Quirino', regionId: 'II' },
  { id: 'III-AUR', name: 'Aurora', regionId: 'III' },
  { id: 'III-BAT', name: 'Bataan', regionId: 'III' },
  { id: 'III-BUL', name: 'Bulacan', regionId: 'III' },
  { id: 'III-NEI', name: 'Nueva Ecija', regionId: 'III' },
  { id: 'III-PAM', name: 'Pampanga', regionId: 'III' },
  { id: 'III-TAR', name: 'Tarlac', regionId: 'III' },
  { id: 'III-ZAM', name: 'Zambales', regionId: 'III' },
  { id: 'IVA-BAT', name: 'Batangas', regionId: 'IVA' },
  { id: 'IVA-CAV', name: 'Cavite', regionId: 'IVA' },
  { id: 'IVA-LAG', name: 'Laguna', regionId: 'IVA' },
  { id: 'IVA-QUE', name: 'Quezon', regionId: 'IVA' },
  { id: 'IVA-RIZ', name: 'Rizal', regionId: 'IVA' },
  { id: 'IVB-MAR', name: 'Marinduque', regionId: 'IVB' },
  { id: 'IVB-OCC', name: 'Occidental Mindoro', regionId: 'IVB' },
  { id: 'IVB-ORI', name: 'Oriental Mindoro', regionId: 'IVB' },
  { id: 'IVB-PAL', name: 'Palawan', regionId: 'IVB' },
  { id: 'IVB-ROM', name: 'Romblon', regionId: 'IVB' },
  { id: 'V-ALB', name: 'Albay', regionId: 'V' },
  { id: 'V-CAS', name: 'Camarines Sur', regionId: 'V' },
  { id: 'V-CAN', name: 'Camarines Norte', regionId: 'V' },
  { id: 'V-CAT', name: 'Catanduanes', regionId: 'V' },
  { id: 'V-MAS', name: 'Masbate', regionId: 'V' },
  { id: 'V-SOR', name: 'Sorsogon', regionId: 'V' },
  { id: 'VI-AKL', name: 'Aklan', regionId: 'VI' },
  { id: 'VI-ANT', name: 'Antique', regionId: 'VI' },
  { id: 'VI-CAP', name: 'Capiz', regionId: 'VI' },
  { id: 'VI-GUI', name: 'Guimaras', regionId: 'VI' },
  { id: 'VI-ILO', name: 'Iloilo', regionId: 'VI' },
  { id: 'VI-NOR', name: 'Negros Occidental', regionId: 'VI' },
  { id: 'VII-BOH', name: 'Bohol', regionId: 'VII' },
  { id: 'VII-CEB', name: 'Cebu', regionId: 'VII' },
  { id: 'VII-NOR', name: 'Negros Oriental', regionId: 'VII' },
  { id: 'VII-SIQ', name: 'Siquijor', regionId: 'VII' },
  { id: 'VIII-BIL', name: 'Biliran', regionId: 'VIII' },
  { id: 'VIII-EAS', name: 'Eastern Samar', regionId: 'VIII' },
  { id: 'VIII-LEY', name: 'Leyte', regionId: 'VIII' },
  { id: 'VIII-NOR', name: 'Northern Samar', regionId: 'VIII' },
  { id: 'VIII-SAM', name: 'Samar', regionId: 'VIII' },
  { id: 'VIII-SLE', name: 'Southern Leyte', regionId: 'VIII' },
  { id: 'IX-ZDN', name: 'Zamboanga del Norte', regionId: 'IX' },
  { id: 'IX-ZDS', name: 'Zamboanga del Sur', regionId: 'IX' },
  { id: 'IX-ZSI', name: 'Zamboanga Sibugay', regionId: 'IX' },
  { id: 'X-BUK', name: 'Bukidnon', regionId: 'X' },
  { id: 'X-CAM', name: 'Camiguin', regionId: 'X' },
  { id: 'X-LDN', name: 'Lanao del Norte', regionId: 'X' },
  { id: 'X-MDC', name: 'Misamis Occidental', regionId: 'X' },
  { id: 'X-MDO', name: 'Misamis Oriental', regionId: 'X' },
  { id: 'XI-COM', name: 'Davao de Oro', regionId: 'XI' },
  { id: 'XI-DAV', name: 'Davao del Norte', regionId: 'XI' },
  { id: 'XI-DAS', name: 'Davao del Sur', regionId: 'XI' },
  { id: 'XI-DAO', name: 'Davao Oriental', regionId: 'XI' },
  { id: 'XI-DOC', name: 'Davao Occidental', regionId: 'XI' },
  { id: 'XII-COT', name: 'Cotabato', regionId: 'XII' },
  { id: 'XII-SAR', name: 'Sarangani', regionId: 'XII' },
  { id: 'XII-SCO', name: 'South Cotabato', regionId: 'XII' },
  { id: 'XII-SUL', name: 'Sultan Kudarat', regionId: 'XII' },
  { id: 'XIII-AGN', name: 'Agusan del Norte', regionId: 'XIII' },
  { id: 'XIII-AGS', name: 'Agusan del Sur', regionId: 'XIII' },
  { id: 'XIII-DIN', name: 'Dinagat Islands', regionId: 'XIII' },
  { id: 'XIII-SDN', name: 'Surigao del Norte', regionId: 'XIII' },
  { id: 'XIII-SDS', name: 'Surigao del Sur', regionId: 'XIII' },
  { id: 'BARMM-BAS', name: 'Basilan', regionId: 'BARMM' },
  { id: 'BARMM-LDS', name: 'Lanao del Sur', regionId: 'BARMM' },
  { id: 'BARMM-MAG', name: 'Maguindanao', regionId: 'BARMM' },
  { id: 'BARMM-SUL', name: 'Sulu', regionId: 'BARMM' },
  { id: 'BARMM-TAW', name: 'Tawi-Tawi', regionId: 'BARMM' },
];

export const cities: City[] = [
  { id: 'NCR-QC', name: 'Quezon City', provinceId: 'NCR-MM' },
  { id: 'NCR-MNL', name: 'City of Manila', provinceId: 'NCR-MM' },
  { id: 'NCR-CAL', name: 'Caloocan City', provinceId: 'NCR-MM' },
  { id: 'NCR-LPC', name: 'Las Pinas City', provinceId: 'NCR-MM' },
  { id: 'NCR-MKT', name: 'Makati City', provinceId: 'NCR-MM' },
  { id: 'NCR-MLA', name: 'Malabon City', provinceId: 'NCR-MM' },
  { id: 'NCR-MDL', name: 'Mandaluyong City', provinceId: 'NCR-MM' },
  { id: 'NCR-MRT', name: 'Marikina City', provinceId: 'NCR-MM' },
  { id: 'NCR-MNT', name: 'Muntinlupa City', provinceId: 'NCR-MM' },
  { id: 'NCR-NVT', name: 'Navotas City', provinceId: 'NCR-MM' },
  { id: 'NCR-PRQ', name: 'Paranaque City', provinceId: 'NCR-MM' },
  { id: 'NCR-PSY', name: 'Pasay City', provinceId: 'NCR-MM' },
  { id: 'NCR-PSG', name: 'Pasig City', provinceId: 'NCR-MM' },
  { id: 'NCR-PTR', name: 'Pateros', provinceId: 'NCR-MM' },
  { id: 'NCR-SJN', name: 'San Juan City', provinceId: 'NCR-MM' },
  { id: 'NCR-TGG', name: 'Taguig City', provinceId: 'NCR-MM' },
  { id: 'NCR-VLC', name: 'Valenzuela City', provinceId: 'NCR-MM' },
  { id: 'CAR-BAG', name: 'Baguio City', provinceId: 'CAR-BEN' },
  { id: 'IVA-ANT', name: 'Antipolo City', provinceId: 'IVA-RIZ' },
  { id: 'IVA-BIN', name: 'Binan City', provinceId: 'IVA-LAG' },
  { id: 'IVA-CAL', name: 'Calamba City', provinceId: 'IVA-LAG' },
  { id: 'IVA-SPC', name: 'San Pedro City', provinceId: 'IVA-LAG' },
  { id: 'IVA-STR', name: 'Santa Rosa City', provinceId: 'IVA-LAG' },
  { id: 'IVA-CAV', name: 'Cavite City', provinceId: 'IVA-CAV' },
  { id: 'IVA-BAC', name: 'Bacoor City', provinceId: 'IVA-CAV' },
  { id: 'IVA-IMC', name: 'Imus City', provinceId: 'IVA-CAV' },
  { id: 'IVA-DSM', name: 'Dasmarinas City', provinceId: 'IVA-CAV' },
  { id: 'IVA-GMA', name: 'General Mariano Alvarez', provinceId: 'IVA-CAV' },
  { id: 'IVA-GEN', name: 'General Trias City', provinceId: 'IVA-CAV' },
  { id: 'IVA-BTG', name: 'Batangas City', provinceId: 'IVA-BAT' },
  { id: 'IVA-LIP', name: 'Lipa City', provinceId: 'IVA-BAT' },
  { id: 'IVA-TAN', name: 'Tanauan City', provinceId: 'IVA-BAT' },
  { id: 'IVA-LUC', name: 'Lucena City', provinceId: 'IVA-QUE' },
  { id: 'III-SFC', name: 'San Fernando City', provinceId: 'III-PAM' },
  { id: 'III-ANC', name: 'Angeles City', provinceId: 'III-PAM' },
  { id: 'III-MAC', name: 'Mabalacat City', provinceId: 'III-PAM' },
  { id: 'III-OLG', name: 'Olongapo City', provinceId: 'III-ZAM' },
  { id: 'III-MLB', name: 'Meycauayan City', provinceId: 'III-BUL' },
  { id: 'III-MLO', name: 'Malolos City', provinceId: 'III-BUL' },
  { id: 'III-SJC', name: 'San Jose del Monte City', provinceId: 'III-BUL' },
  { id: 'VII-CEB', name: 'Cebu City', provinceId: 'VII-CEB' },
  { id: 'VII-LAP', name: 'Lapu-Lapu City', provinceId: 'VII-CEB' },
  { id: 'VII-MAN', name: 'Mandaue City', provinceId: 'VII-CEB' },
  { id: 'VII-TLS', name: 'Talisay City', provinceId: 'VII-CEB' },
  { id: 'VII-TAG', name: 'Tagbilaran City', provinceId: 'VII-BOH' },
  { id: 'VII-DUM', name: 'Dumaguete City', provinceId: 'VII-NOR' },
  { id: 'VI-ILO', name: 'Iloilo City', provinceId: 'VI-ILO' },
  { id: 'VI-BAC', name: 'Bacolod City', provinceId: 'VI-NOR' },
  { id: 'X-CDO', name: 'Cagayan de Oro City', provinceId: 'X-MDO' },
  { id: 'XI-DAV', name: 'Davao City', provinceId: 'XI-DAS' },
  { id: 'XII-GEN', name: 'General Santos City', provinceId: 'XII-SCO' },
  { id: 'IX-ZAM', name: 'Zamboanga City', provinceId: 'IX-ZDS' },
];

export const barangays: Barangay[] = [
  { id: 'NCR-MKT-BEL', name: 'Bel-Air', cityId: 'NCR-MKT' },
  { id: 'NCR-MKT-CMF', name: 'Carmona', cityId: 'NCR-MKT' },
  { id: 'NCR-MKT-FOR', name: 'Forbes Park', cityId: 'NCR-MKT' },
  { id: 'NCR-MKT-GUA', name: 'Guadalupe Nuevo', cityId: 'NCR-MKT' },
  { id: 'NCR-MKT-GUV', name: 'Guadalupe Viejo', cityId: 'NCR-MKT' },
  { id: 'NCR-MKT-KAS', name: 'Kasilawan', cityId: 'NCR-MKT' },
  { id: 'NCR-MKT-LEG', name: 'Legaspi Village', cityId: 'NCR-MKT' },
  { id: 'NCR-MKT-MAG', name: 'Magallanes', cityId: 'NCR-MKT' },
  { id: 'NCR-MKT-OLY', name: 'Olympia', cityId: 'NCR-MKT' },
  { id: 'NCR-MKT-PAL', name: 'Palanan', cityId: 'NCR-MKT' },
  { id: 'NCR-MKT-PIO', name: 'Pio del Pilar', cityId: 'NCR-MKT' },
  { id: 'NCR-MKT-POB', name: 'Poblacion', cityId: 'NCR-MKT' },
  { id: 'NCR-MKT-SAL', name: 'Salcedo Village', cityId: 'NCR-MKT' },
  { id: 'NCR-MKT-SAN', name: 'San Antonio', cityId: 'NCR-MKT' },
  { id: 'NCR-MKT-SAI', name: 'San Isidro', cityId: 'NCR-MKT' },
  { id: 'NCR-MKT-SAL2', name: 'San Lorenzo', cityId: 'NCR-MKT' },
  { id: 'NCR-MKT-STA', name: 'Santa Cruz', cityId: 'NCR-MKT' },
  { id: 'NCR-MKT-URD', name: 'Urdaneta', cityId: 'NCR-MKT' },
  { id: 'NCR-MKT-VAL', name: 'Valenzuela', cityId: 'NCR-MKT' },
  { id: 'NCR-QC-AMU', name: 'Amulung', cityId: 'NCR-QC' },
  { id: 'NCR-QC-BAG', name: 'Bagbag', cityId: 'NCR-QC' },
  { id: 'NCR-QC-BAH', name: 'Bahay Toro', cityId: 'NCR-QC' },
  { id: 'NCR-QC-BAL', name: 'Balingasa', cityId: 'NCR-QC' },
  { id: 'NCR-QC-BAT', name: 'Batasan Hills', cityId: 'NCR-QC' },
  { id: 'NCR-QC-COM', name: 'Commonwealth', cityId: 'NCR-QC' },
  { id: 'NCR-QC-CUB', name: 'Cubao', cityId: 'NCR-QC' },
  { id: 'NCR-QC-DIL', name: 'Diliman', cityId: 'NCR-QC' },
  { id: 'NCR-QC-ERM', name: 'E. Rodriguez', cityId: 'NCR-QC' },
  { id: 'NCR-QC-FAV', name: 'Fairview', cityId: 'NCR-QC' },
  { id: 'NCR-QC-GRH', name: 'Greater Lagro', cityId: 'NCR-QC' },
  { id: 'NCR-QC-HOL', name: 'Holy Spirit', cityId: 'NCR-QC' },
  { id: 'NCR-QC-KAM', name: 'Kamuning', cityId: 'NCR-QC' },
  { id: 'NCR-QC-LAG', name: 'Lagro', cityId: 'NCR-QC' },
  { id: 'NCR-QC-NOV', name: 'Novaliches Proper', cityId: 'NCR-QC' },
  { id: 'NCR-QC-PRJ', name: 'Project 6', cityId: 'NCR-QC' },
  { id: 'NCR-QC-SFH', name: 'San Francisco del Monte', cityId: 'NCR-QC' },
  { id: 'NCR-QC-TIM', name: 'Tatalon', cityId: 'NCR-QC' },
  { id: 'NCR-QC-TON', name: 'Tandang Sora', cityId: 'NCR-QC' },
  { id: 'NCR-QC-UPD', name: 'UP Diliman', cityId: 'NCR-QC' },
  { id: 'NCR-MNL-BIN', name: 'Binondo', cityId: 'NCR-MNL' },
  { id: 'NCR-MNL-ERM', name: 'Ermita', cityId: 'NCR-MNL' },
  { id: 'NCR-MNL-INT', name: 'Intramuros', cityId: 'NCR-MNL' },
  { id: 'NCR-MNL-MAL', name: 'Malate', cityId: 'NCR-MNL' },
  { id: 'NCR-MNL-PAN', name: 'Paco', cityId: 'NCR-MNL' },
  { id: 'NCR-MNL-PAD', name: 'Pandacan', cityId: 'NCR-MNL' },
  { id: 'NCR-MNL-QUI', name: 'Quiapo', cityId: 'NCR-MNL' },
  { id: 'NCR-MNL-SAM', name: 'Sampaloc', cityId: 'NCR-MNL' },
  { id: 'NCR-MNL-SAN', name: 'San Andres', cityId: 'NCR-MNL' },
  { id: 'NCR-MNL-SMC', name: 'San Miguel', cityId: 'NCR-MNL' },
  { id: 'NCR-MNL-SNK', name: 'San Nicolas', cityId: 'NCR-MNL' },
  { id: 'NCR-MNL-SAC', name: 'Santa Ana', cityId: 'NCR-MNL' },
  { id: 'NCR-MNL-STC', name: 'Santa Cruz', cityId: 'NCR-MNL' },
  { id: 'NCR-MNL-STM', name: 'Santa Mesa', cityId: 'NCR-MNL' },
  { id: 'NCR-MNL-TON', name: 'Tondo', cityId: 'NCR-MNL' },
  { id: 'NCR-PSG-BAG', name: 'Bagong Ilog', cityId: 'NCR-PSG' },
  { id: 'NCR-PSG-BGT', name: 'Bagong Tanyag', cityId: 'NCR-PSG' },
  { id: 'NCR-PSG-CAP', name: 'Kapitolyo', cityId: 'NCR-PSG' },
  { id: 'NCR-PSG-MAN', name: 'Manggahan', cityId: 'NCR-PSG' },
  { id: 'NCR-PSG-MYB', name: 'Maybunga', cityId: 'NCR-PSG' },
  { id: 'NCR-PSG-ORT', name: 'Ortigas', cityId: 'NCR-PSG' },
  { id: 'NCR-PSG-PLY', name: 'Palatiw', cityId: 'NCR-PSG' },
  { id: 'NCR-PSG-PIN', name: 'Pinagbuhatan', cityId: 'NCR-PSG' },
  { id: 'NCR-PSG-ROB', name: 'Rosario', cityId: 'NCR-PSG' },
  { id: 'NCR-PSG-SAG', name: 'Sagad', cityId: 'NCR-PSG' },
  { id: 'NCR-PSG-SAN', name: 'San Antonio', cityId: 'NCR-PSG' },
  { id: 'NCR-PSG-SJO', name: 'San Joaquin', cityId: 'NCR-PSG' },
  { id: 'NCR-PSG-SMR', name: 'Santa Rosa', cityId: 'NCR-PSG' },
  { id: 'NCR-PSG-UGA', name: 'Ugong', cityId: 'NCR-PSG' },
  { id: 'NCR-TGG-BAG', name: 'Bagumbayan', cityId: 'NCR-TGG' },
  { id: 'NCR-TGG-BGC', name: 'Bonifacio Global City', cityId: 'NCR-TGG' },
  { id: 'NCR-TGG-CAL', name: 'Calzada', cityId: 'NCR-TGG' },
  { id: 'NCR-TGG-CEN', name: 'Central Bicutan', cityId: 'NCR-TGG' },
  { id: 'NCR-TGG-FOR', name: 'Fort Bonifacio', cityId: 'NCR-TGG' },
  { id: 'NCR-TGG-HAP', name: 'Hagonoy', cityId: 'NCR-TGG' },
  { id: 'NCR-TGG-LIG', name: 'Ligid-Tipas', cityId: 'NCR-TGG' },
  { id: 'NCR-TGG-LOW', name: 'Lower Bicutan', cityId: 'NCR-TGG' },
  { id: 'NCR-TGG-NAP', name: 'Napindan', cityId: 'NCR-TGG' },
  { id: 'NCR-TGG-PAL', name: 'Palingon', cityId: 'NCR-TGG' },
  { id: 'NCR-TGG-SAM', name: 'San Miguel', cityId: 'NCR-TGG' },
  { id: 'NCR-TGG-SIG', name: 'Signal Village', cityId: 'NCR-TGG' },
  { id: 'NCR-TGG-TUA', name: 'Tuktukan', cityId: 'NCR-TGG' },
  { id: 'NCR-TGG-UPB', name: 'Upper Bicutan', cityId: 'NCR-TGG' },
  { id: 'NCR-TGG-USU', name: 'Ususan', cityId: 'NCR-TGG' },
  { id: 'NCR-TGG-WES', name: 'Western Bicutan', cityId: 'NCR-TGG' },
];

export function getProvincesByRegion(regionId: string): Province[] {
  return provinces.filter((p) => p.regionId === regionId);
}

export function getCitiesByProvince(provinceId: string): City[] {
  return cities.filter((c) => c.provinceId === provinceId);
}

export function getBarangaysByCity(cityId: string): Barangay[] {
  return barangays.filter((b) => b.cityId === cityId);
}

export function getRegionById(id: string): Region | undefined {
  return regions.find((r) => r.id === id);
}

export function getProvinceById(id: string): Province | undefined {
  return provinces.find((p) => p.id === id);
}

export function getCityById(id: string): City | undefined {
  return cities.find((c) => c.id === id);
}

export function getBarangayById(id: string): Barangay | undefined {
  return barangays.find((b) => b.id === id);
}

export function getFullAddress(barangayId: string, streetAddress?: string): string {
  const barangay = getBarangayById(barangayId);
  if (!barangay) return streetAddress || '';

  const city = getCityById(barangay.cityId);
  if (!city) return `${streetAddress || ''}, ${barangay.name}`;

  const province = getProvinceById(city.provinceId);
  if (!province) return `${streetAddress || ''}, ${barangay.name}, ${city.name}`;

  const parts = [streetAddress, barangay.name, city.name, province.name].filter(Boolean);

  return parts.join(', ');
}
